name: Setup
description: Setup environment for build
runs:
  using: 'composite'
  steps:
    - name: Setup env variables
      shell: bash
      run: export CARGO_TERM_COLOR=always

    - name: Use Rust
      shell: bash
      run: rustup toolchain install stable --profile minimal

    - name: Install Just runner, LLD (fast linker), and libdbus (for keyring)
      shell: bash
      run: sudo apt-get update && sudo apt-get install -y just lld libdbus-1-dev

    - name: Use Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '23.7'

    - name: Rust cache
      uses: Swatinem/rust-cache@v2

    - name: Install JS modules
      shell: bash
      run: ELECTRON_SKIP_BINARY_DOWNLOAD=1 npm ci
