name: Setup
description: Setup environment for build
inputs:
  packages:
    description: 'Additional packages to install'
    required: false
    default: ''
  targets:
    description: 'Additional rustup targets to install'
    required: false
    default: ''
runs:
  using: 'composite'
  steps:
    - name: Install Just runner and LLD (fast linker)
      shell: bash
      run: sudo apt-get update && sudo apt-get install -y just lld ${{ inputs.packages }}

    - name: Setup Cargo environment variables
      shell: bash
      run: |
        echo "CARGO_TERM_COLOR=always" >> $GITHUB_ENV

        # Disable incremental compilation for faster from-scratch builds
        echo "CARGO_INCREMENTAL=0" >> $GITHUB_ENV

        # Disable debug info
        echo "CARGO_PROFILE_TEST_DEBUG=0" >> $GITHUB_ENV

    - name: Use Rust
      uses: actions-rust-lang/setup-rust-toolchain@v1
      with:
        target: ${{ inputs.targets }}
        components: clippy
        rustflags:

    - name: Install Rust dependencies
      shell: bash
      run: cargo fetch --locked

    - name: Use Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '23.7'
        cache: npm

    - name: Install JS modules
      shell: bash
      run: ELECTRON_SKIP_BINARY_DOWNLOAD=1 npm ci
