name: Setup
description: Setup environment for build
runs:
  using: 'composite'
  steps:
    - name: Setup env variables
      shell: bash
      run: echo "CARGO_TERM_COLOR=always" >> $GITHUB_ENV

    - name: Use Rust
      shell: bash
      run: rustup toolchain install stable --profile minimal

    - name: Add target for Android build
      shell: bash
      run: rustup target add aarch64-linux-android

    - name: Add target for Windows build
      shell: bash
      run: rustup target add x86_64-pc-windows-gnu

    - name: Install cargo-ndk (build & cache for Android app build)
      shell: bash
      run: cargo install --locked cargo-ndk

    - name: Install Just runner, LLD (fast linker), libdbus (for keyring), and MinGW for Windows cross-compilation
      shell: bash
      run: sudo apt-get update && sudo apt-get install -y just lld libdbus-1-dev mingw-w64

    - name: Use Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '23.7'

    - name: Rust cache
      uses: Swatinem/rust-cache@v2

    - name: Install JS modules
      shell: bash
      run: ELECTRON_SKIP_BINARY_DOWNLOAD=1 npm ci
