[workspace]
members = [
  "arhiv-core",
  "arhiv-ui3",
  "arhiv-scraper",
  "arhiv-bin",
  "arhiv-utils",
  "binutils",
  "rs-utils",
  "scraper"
]

exclude = [
  "app-shell"
]

# speed up debug builds
[profile.dev]
debug = 0
