#!/usr/bin/env -S node

require('tsconfig-paths').register({
  baseUrl: './',
  paths: require('./tsconfig.json').compilerOptions.paths
});

require('ts-node').register({
  files: true,
  compilerOptions: {
    module: 'commonjs',
  },
});

const path = require('path');

global.__DEVELOPMENT__ = process.env.NODE_ENV !== 'production';
global.__SERVER__ = true;

const { default: run } = require(path.join(process.cwd(), process.argv[2]));

Promise.resolve(run(...process.argv.slice(3))).catch((e) => {
  console.error('process failed', e);
  process.exit(2);
});
