#!/usr/bin/env -S node

// make nodejs support TypeScript's type aliases
// https://github.com/Microsoft/TypeScript/issues/15479#issuecomment-468122916
require('tsconfig-paths').register({
  baseUrl: './',
  paths: require('./tsconfig.json').compilerOptions.paths
});

const isProduction = process.env.NODE_ENV === 'production'

require('ts-node').register({
  transpileOnly: isProduction,
  compilerOptions: {
    module: 'commonjs',
    types: ['node'],
  },
});

const path = require('path');

const { default: run } = require(path.join(process.cwd(), process.argv[2]));

Promise.resolve(run(...process.argv.slice(3))).catch((e) => {
  console.error('process failed', e);
  process.exit(2);
});
