[package]
name = "arhiv-utils"
version = "0.1.0"
edition = "2018"

[dependencies]
log = "0.4.13"
env_logger = "0.8.2"
anyhow = "1.0.38"
tokio = { version = "1.0.2", features = ["macros"] }

arhiv = { path = "../arhiv" }
rs-utils = { path = "../rs-utils" }
