[package]
name = "arhiv-utils"
version = "0.1.0"
edition = "2018"

[dependencies]
tracing = "0.1"

anyhow = "1.0.38"
rand = "0.8.2"
serde_json = "1.0.61"
tokio = { version = "1.0.2", features = ["macros"] }

arhiv = { path = "../arhiv" }
rs-utils = { path = "../rs-utils" }
