[package]
name = "arhiv"
version = "0.3.0"
authors = ["mbme"]
edition = "2018"
default-run = "arhiv"

[lib]
doctest = false

[features]
production-mode = []

[dependencies]
anyhow = "1.0.38"

clap = { version = "2.33.3", features = ["color"] }

serde = { version = "1.0.120", features = ["derive", "rc"] }
serde_json = "1.0.61"

chrono = { version = "0.4.19", features = ["serde"] }

lazy_static = "1.4.0"

futures = "0.3.12"
tokio = { version = "1.0.2", features = ["macros", "signal", "rt-multi-thread"] }
tokio-util = { version = "0.6.1", features = ["compat"] }

reqwest = { version = "0.11.0", features = ["json", "stream"] }
nanoid = "0.3.0"
pulldown-cmark  = "0.8.0"

warp = "0.3.0"
mime_guess = "2.0.3"

rusqlite = { version = "0.24.2", features = ["chrono", "serde_json", "functions"] }

rs-utils = { path = "../rs-utils" }
arhiv-ui = { path = "../arhiv-ui" }
