[package]
name = "arhiv"
version = "0.1.0"
authors = ["mbme"]
edition = "2018"
default-run = "arhiv"

[dependencies]
log = "0.4"
env_logger = "0.7"

anyhow = "1.0"

clap = { version = "2.33", features = ["color"] }

serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"

uuid = { version = "0.8", features = ["v4"]}

chrono = { version = "0.4", features = ["serde"] }

tokio = { version = "0.2", features = ["macros"] }
tokio-util = "0.3.1"
reqwest = { version = "0.10", features = ["json", "stream"] }
warp = "0.2"
bytes = "0.5"

rusqlite = { version = "0.24", features = ["chrono", "serde_json", "functions"] }
