[package]
name = "arhiv-replica"
version = "0.1.0"
edition = "2018"

[dependencies]
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
anyhow = "1.0"
reqwest = { version = "0.10", features = ["blocking"] }
chrono = { version = "0.4", features = ["serde"] }
tokio = { version = "0.2", features = ["macros"] }
warp = "0.2"

[dependencies.clap]
version = "2.33"
features = [ "color" ]

[dependencies.uuid]
version = "0.8"
features = ["v4"]
