[package]
name = "arhiv"
version = "0.0.0"
edition = "2021"
authors = ["mbme"]
publish = false

[lib]
doctest = false

[features]
production-mode = ["baza/production-mode"]

[dependencies]
baza = { path = "../baza" }
rs-utils = { path = "../rs-utils" }
scraper = { path = "../scraper" }

anyhow.workspace = true
tracing.workspace = true

serde.workspace = true
serde_json.workspace = true

tokio.workspace = true
tokio-util.workspace = true
tokio-stream.workspace = true

axum.workspace = true

rust-embed= { version = "8", features = ["interpolate-folder-path"]}

[build-dependencies]
rs-utils = { path = "../rs-utils" }
