[package]
name = "rs-utils"
version = "0.1.0"
edition = "2018"

[features]
production-mode = []

[dependencies]
log = "0.4"
fern = "0.6"

anyhow = "1.0.38"

tokio = { version = "1.0.2", features = ["macros", "fs"] }
tokio-util = { version = "0.6.1", features = ["compat", "codec"] }

sha2 = "0.9.2"
uuid = { version = "0.8.2", features = ["v4"] }
chrono = { version = "0.4.19", features = ["serde"] }
rand = "0.8.2"
