[package]
name = "rs-utils"
version = "0.0.0"
edition = "2021"
authors = ["mbme"]
publish = false

[dependencies]
log = "0.4"
fern = "0.6"

anyhow = "1.0.38"

tokio = { version = "1", features = ["macros", "fs"] }
tokio-util = { version = "0.6", features = ["compat", "codec"] }

blake3 = "1.2.0"
base64 = "0.13.0"
uuid = { version = "0.8.2", features = ["v4"] }
chrono = { version = "0.4.19", features = ["serde"] }
rand = "0.8.2"

serde = { version = "1", features = ["derive"] }
serde_json = "1"

hyper = { version = "0.14", features = ["http1", "server"] }
routerify = "2"
mime_guess = "2"
infer = "0.5"
form_urlencoded = "1"
url = "2.2.2"

futures = "0.3"
reqwest = { version = "0.11", features = ["json", "stream"] }

shellexpand = "2.1.0"
