[package]
name = "rs-utils"
version = "0.1.0"
edition = "2018"

[features]
production-mode = []

[dependencies]
log = "0.4.11"
env_logger = "0.8.2"

anyhow = "1.0.36"

tokio = { version = "0.2", features = ["macros", "fs"] }
tokio-util = { version  = "0.3.1", features = ["compat", "codec"]}

sha2 = "0.9.2"
uuid = { version = "0.8.1", features = ["v4"] }
chrono = { version = "0.4.19", features = ["serde"] }
rand = "0.8.0"
