[package]
name = "rs-utils"
version = "0.0.0"
edition = "2021"
authors = ["mbme"]
publish = false

[lints]
workspace = true

[dependencies]
log = "0.4"
tracing.workspace = true
tracing-subscriber.workspace = true
tracing-android = "0.2"

anyhow.workspace = true

futures.workspace = true
tokio.workspace = true
tokio-util.workspace = true

serde.workspace = true
serde_json.workspace = true

hyper.workspace = true
reqwest.workspace = true
axum.workspace = true
axum-extra.workspace = true
axum-server.workspace = true

rand.workspace = true
lazy_static.workspace = true
chrono.workspace = true
blake3 = "1.2.0"
base64 = "0.21.0"
mime_guess = "2"
infer = "0.15"
url = "2.2.2"
regex = "1.5.4"
image = { version = "0.24.7", features = ["webp-encoder"]}
shellexpand = "3.0.0"
which = "6.0"
nanoid = "0.4.0"
mdns-sd = "0.10"
gethostname = "0.4.3"
rayon = "1.8.0"
rcgen = "0.12"
