[package]
name = "rs-utils"
version = "0.1.0"
edition = "2018"

[dependencies]
log = "0.4"
env_logger = "0.7"

anyhow = "1.0"

tokio = { version = "0.2", features = ["macros", "fs"] }
tokio-util = { version  = "0.3.1", features = ["compat", "codec"]}

sha2 = "0.9.1"
uuid = { version = "0.8", features = ["v4"]}
chrono = { version = "0.4", features = ["serde"] }
