[package]
name = "rs-utils"
version = "0.0.0"
edition = "2021"
authors = ["mbme"]
publish = false

[lints]
workspace = true

[dependencies]
log = "0.4"
tracing.workspace = true
tracing-subscriber.workspace = true

anyhow.workspace = true

futures.workspace = true
tokio.workspace = true
tokio-util.workspace = true

serde.workspace = true
serde_json.workspace = true

hyper.workspace = true
reqwest.workspace = true
axum.workspace = true
axum-extra.workspace = true
axum-server.workspace = true

rand.workspace = true
chrono.workspace = true
blake3 = "1.2.0" # fast file hash
ring.workspace = true
secstr = { version = "0.5", features = ["serde"] } # securely store secrets in memory
data-encoding = "2" # base64, hex encodings
mime_guess = "2"
infer = "0.16"
url = "2.2.2"
regex = "1.5.4"
image = "0.25" # encode/decode/scale images, guess image types
shellexpand = "3.0.0"
which = "6.0"
nanoid = "0.4.0" # generate short unique global ids
mdns-sd = "0.11"
gethostname = "0.5"
rayon = "1.8.0"
rcgen = "0.13" # generate self-signed certificates
pem = "*" # serialize TLS private key & certificate into PEM file
tokio-rustls.workspace = true
tower.workspace = true
fslock = "0.2"

[target.'cfg(android)'.dependencies]
tracing-android = "0.2"
