[package]
name = "rs-utils"
version = "0.0.0"
edition = "2021"
authors = ["mbme"]
publish = false

[dependencies]
log = "0.4"
fern = "0.6"

anyhow.workspace = true

tokio.workspace = true
tokio-util.workspace = true

blake3 = "1.2.0"
base64 = "0.13.0"
chrono = { version = "0.4.19", features = ["serde"] }
rand.workspace = true
lazy_static.workspace = true

serde.workspace = true
serde_json.workspace = true

hyper.workspace = true
routerify.workspace = true

mime_guess = "2"
infer = "0.9"
form_urlencoded = "1"
url = "2.2.2"
regex = "1.5.4"
imagesize = "0.10.0"

futures.workspace = true
reqwest.workspace = true

shellexpand = "2.1.0"
which = "4.2.2"
