[package]
name = "scraper"
version = "0.0.0"
edition = "2021"
authors = ["mbme"]
publish = false

[dependencies]
rs-utils = { path = "../rs-utils" }

anyhow = "1"

serde = { version = "1", features = ["derive"] }
serde_json = "1"

tokio = { version = "1", features = ["macros", "signal", "rt-multi-thread"] }

fantoccini = "0.19"
url = "2.2"
http = "0.2"
cookie = "0.16"

[dev-dependencies]
insta = { version = "1", features = ["redactions", "json"] }

[build-dependencies]
rs-utils = { path = "../rs-utils" }
