[package]
name = "arhiv-desktop-gtk"
version = "0.1.0"
edition = "2018"

[dependencies.webkit2gtk]
version = "0.9.0"
features = ["v2_16"]

[dependencies.gtk]
version = "0.8.0"
features = ["v3_16"]

[dependencies.gio]
version = ""
features = ["v2_44"]
