[package]
name = "binutils"
version = "0.0.0"
edition = "2021"
authors = ["mbme"]
publish = false

[dependencies]
anyhow = "1.0.38"
clap = { version = "3.0", features = ["color"] }

rs-utils = { path = "../rs-utils" }
