[package]
name = "binutils"
version = "0.0.0"
edition = "2021"
authors = ["mbme"]
publish = false

[dependencies]
anyhow = "1.0.38"
clap = { version = "3.2", features = ["color", "derive"] }

serde = { version = "1", features = ["derive"] }
serde_json = "1"

rs-utils = { path = "../rs-utils" }
scraper = { path = "../scraper" }
