[package]
name = "binutils"
version = "0.6.0"
edition = "2021"
authors = ["mbme"]
publish = false

# speed up debug builds
[profile.dev]
debug = 0

[dependencies]
anyhow = "1.0.38"
clap = { version = "2.33.3", features = ["color"] }
regex = "1.4.3"
lazy_static = "1.4.0"

rs-utils = { path = "../rs-utils" }

serde = { version = "1.0.120", features = ["derive"] }
serde_json = "1.0.61"

# gtk
gtk = { version = "0.14.1" }
gio = { version = "0.14.3" }
