[package]
name = "binutils"
version = "0.4.0"
edition = "2018"

[dependencies]
anyhow = "1.0.38"
clap = { version = "2.33.3", features = ["color"] }
regex = "1.4.3"
lazy_static = "1.4.0"

rs-utils = { path = "../rs-utils" }
