[package]
name = "binutils"
version = "0.3.0"
edition = "2018"

[dependencies]
log = "0.4.11"
env_logger = "0.8.2"
anyhow = "1.0.36"
clap = { version = "2.33.3", features = ["color"] }
regex = "1.4.2"
lazy_static = "1.4.0"

rs-utils = { path = "../rs-utils" }
