[package]
name = "binutils"
version = "0.3.0"
edition = "2018"

[dependencies]
log = "0.4"
env_logger = "0.7"
anyhow = "1.0"
clap = { version = "2.33", features = ["color"] }
regex = "1"
lazy_static = "1"

rs-utils = { path = "../rs-utils" }
