[package]
name = "binutils"
version = "0.10.1"
edition = "2021"
authors = ["mbme"]
publish = false

[dependencies]
anyhow = "1.0.38"
clap = { version = "3.0", features = ["color", "cargo"] }

rs-utils = { path = "../rs-utils" }
