[package]
name = "binutils"
version = "0.0.0"
edition = "2021"
authors = ["mbme"]
publish = false

[features]
production-mode = ["arhiv-ui/production-mode"]

[dependencies]
anyhow.workspace = true

clap = { version = "4", features = ["derive", "env"] }
clap_complete = "4.0"

serde.workspace = true
serde_json.workspace = true

tokio.workspace = true

baza = { path = "../baza" }
rs-utils = { path = "../rs-utils" }
scraper = { path = "../scraper" }
arhiv-ui = { path = "../arhiv-ui" }
