[package]
name = "binutils"
version = "0.0.0"
edition = "2021"
authors = ["mbme"]
publish = false

[features]
production-mode = ["arhiv-core/production-mode"]

[dependencies]
anyhow = "1.0"

clap = { version = "4", features = ["derive", "env"] }
clap_complete = "4.0"

serde = { version = "1", features = ["derive"] }
serde_json = "1"

tokio = { version = "1", features = ["macros", "signal", "rt-multi-thread"] }

rs-utils = { path = "../rs-utils" }
scraper = { path = "../scraper" }
arhiv-core = { path = "../arhiv-core" }
arhiv-ui3 = { path = "../arhiv-ui3" }
