mod catalog_page;
mod document_page;
mod edit_document_page;
mod erase_document_confirmation_dialog;
mod index_page;
mod new_document_page;
mod new_document_variants_page;
mod pick_document_modal;
mod pick_file_confirmation_modal;
mod pick_file_modal;
mod scrape_modal;

pub use catalog_page::*;
pub use document_page::*;
pub use edit_document_page::*;
pub use erase_document_confirmation_dialog::*;
pub use index_page::*;
pub use new_document_page::*;
pub use new_document_variants_page::*;
pub use pick_document_modal::*;
pub use pick_file_confirmation_modal::*;
pub use pick_file_modal::*;
pub use scrape_modal::*;
