[build]
rustflags = ["-Clink-arg=-fuse-ld=lld"]


# target native CPU for linux builds
[target.x86_64-unknown-linux-gnu]
rustflags = ["-Ctarget-cpu=native", "-Clink-arg=-fuse-ld=lld"]

# statically link C runtime to avoid external dll dependencies (MinGW links dynamically by default)
[target.x86_64-pc-windows-gnu]
rustflags = ["-C", "target-feature=+crt-static"]
