[package]
name = "arhiv-notes"
version = "0.1.0"
edition = "2018"
default-run = "arhiv-notes"

[dependencies]
log = "0.4"
env_logger = "0.7"
anyhow = "1.0"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
app-shell = { path = "../app-shell" }
arhiv = { path = "../arhiv" }
