[package]
name = "arhiv-core"
version = "0.12.0"
authors = ["mbme"]
edition = "2018"
publish = false

[lib]
doctest = false

[features]
production-mode = []

[dependencies]
anyhow = "1.0.38"

serde = { version = "1", features = ["derive", "rc"] }
serde_json = "1"

chrono = { version = "0.4", features = ["serde"] }

lazy_static = "1.4"

aho-corasick = "0.7"

futures = "0.3.12"
tokio = { version = "1", features = ["macros", "signal", "rt-multi-thread"] }
tokio-util = { version = "0.6.1", features = ["compat"] }

reqwest = { version = "0.11", features = ["json", "stream"] }
nanoid = "0.4.0"
pulldown-cmark = { version = "0.8", default-features = false, features = ["simd"] }

hyper = { version = "0.14", features = ["http1", "server"] }
routerify = "2"

rusqlite = { version = "0.25", features = ["chrono", "serde_json", "functions"] }

rs-utils = { path = "../rs-utils" }
