[package]
name = "baza"
version = "0.0.0"
edition = "2021"
authors = ["mbme"]
publish = false

[lib]
doctest = false

[features]
production-mode = []

[dependencies]
anyhow.workspace = true
tracing.workspace = true

serde.workspace = true
serde_json.workspace = true

futures.workspace = true
tokio.workspace = true

aho-corasick = "1.1.0"

pulldown-cmark = { version = "0.9", default-features = false, features = ["simd", "serde"] }

rusqlite = { version = "0.30", features = ["chrono", "serde_json", "functions", "collation"] }

rs-utils = { path = "../rs-utils" }

fslock = "0.2.1"

reqwest.workspace = true
axum.workspace = true

[dev-dependencies]
insta.workspace = true
