[package]
name = "arhiv-ui"
version = "0.1.0"
edition = "2018"

[features]
production-mode = ["arhiv/production-mode"]

[dependencies]
log = "0.4.11"
env_logger = "0.8.2"
anyhow = "1.0.36"
serde = { version = "1.0.118", features = ["derive"] }
serde_json = "1.0.60"
tokio = { version = "0.2", features = ["macros"] }

app-shell = { path = "../app-shell" }
arhiv = { path = "../arhiv" }
arhiv-modules = { path = "../arhiv-modules" }
rs-utils = { path = "../rs-utils" }
