[package]
name = "arhiv-ui"
version = "0.1.0"
edition = "2018"

[features]
production-mode = ["arhiv/production-mode"]

[dependencies]
log = "0.4.13"
env_logger = "0.8.2"
anyhow = "1.0.38"
serde = { version = "1.0.120", features = ["derive"] }
serde_json = "1.0.61"
tokio = { version = "1.0.2", features = ["macros"] }
async-trait = "0.1.42"

app-shell = { path = "../app-shell" }
arhiv = { path = "../arhiv" }
rs-utils = { path = "../rs-utils" }
