name: Check code

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup environment
        uses: ./.github/actions/setup

      - name: Lint & test Rust
        run: cargo clippy --all-targets --all-features -- -D warnings && cargo test

      - name: Lint and test TS
        run: npm run check
