name: Check code

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-24.04

    steps:
      - name: Checkout code
        uses: actions/checkout@v7.0.1

      - name: Setup environment
        uses: ./.github/actions/setup

      - name: Lint & test Rust
        run: just check-rs

      - name: Lint and test TS
        run: just check-ts
