name: Check code

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # selecting a toolchain either by action or manual `rustup` calls should happen
      # before the plugin, as the cache uses the current rustc version as its cache key
      - run: rustup toolchain install stable --profile minimal

      - uses: actions/checkout@v3
      - uses: extractions/setup-just@v1
      - uses: Swatinem/rust-cache@v2

      - name: Install JS modules
        run: yarn install --immutable --immutable-cache

      - name: Lint & test Rust
        run: just check-rs

      - name: Lint and test TS
        run: just check-ts
