name: Check code

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # toolchain must be selected before the rust-cache init
      - name: Use Rust
        run: rustup toolchain install stable --profile minimal

      - uses: actions/checkout@v4
      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '21.x'

      - uses: Swatinem/rust-cache@v2

      - name: Install JS modules
        run: npm ci

      - name: Lint & test Rust
        run: cargo clippy --all-targets --all-features -- -D warnings && cargo test

      - name: Lint and test TS
        run: npm run check
