name: Rust

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
      - name: Check & lint Rust
        run: cargo clippy --verbose --all-targets --all-features -- -D warnings
      - name: Run Rust tests
        run: cargo test --verbose
      - name: Install JS modules
        run: yarn install
      - name: Check JS & TS formatting
        run: yarn run check-fmt
      - name: Lint Arhiv UI
        run: yarn workspace arhiv-ui3 run lint
      - name: Lint Arhiv Scraper
        run: yarn workspace arhiv-scraper run lint
