name: Check code

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # toolchain must be selected before the rust-cache init
      - run: rustup toolchain install stable --profile minimal

      - uses: actions/checkout@v3
      - uses: Swatinem/rust-cache@v2

      - name: Install JS modules
        run: yarn install --immutable --immutable-cache

      - name: Lint & test Rust
        run: cargo clippy --all-targets --all-features -- -D warnings && cargo test

      - name: Lint and test TS
        run: yarn run check-fmt && yarn workspaces run lint && yarn workspaces run compiler-errors
