name: Build & Release Arhiv

on:
  workflow_dispatch:
  push:
    tags:
      - '*'

jobs:
  build-and-publish:
    runs-on: ubuntu-latest
    environment:
      name: Release

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 100 # fetch last 100 commits so that git describe --tags works
          fetch-tags: true
          # this is necessary due to using both fetch-depth & fetch-tags https://github.com/actions/checkout/issues/1467
          ref: ${{ github.ref }}

      - name: Setup environment
        uses: ./.github/actions/setup
        with:
          packages: mingw-w64 # MinGW for Windows cross-compilation
          targets: aarch64-linux-android x86_64-pc-windows-gnu # Android & Windows targets for rustup

      - name: Build Linux CLI
        run: just prod-build

      - name: Build Windows CLI
        run: just prod-build-windows

      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: '17' # Gradle plugin target
          cache: 'gradle'

      - name: Setup Android SDK
        uses: android-actions/setup-android@v3
        with:
          packages: ''
          log-accepted-android-sdk-licenses: false

      - name: Decode keystore
        run: |
          echo "${{ secrets.RELEASE_KEYSTORE_BASE64 }}" | base64 -d > arhiv-android/release.keystore

      - name: Write keystore.properties
        run: |
          cat <<EOF > arhiv-android/keystore.properties
          storeFile=$PWD/arhiv-android/release.keystore
          storePassword=${{ secrets.KEY_STORE_PASS }}
          keyAlias=${{ secrets.KEY_ALIAS }}
          keyPassword=${{ secrets.KEY_PASS }}
          EOF

      - name: Build Android Native Libs
        run: just prod-build-android-libs

      - name: Build & Sign Release APK
        run: just prod-build-android-app

      - name: Publish to GitHub Release
        uses: ncipollo/release-action@v1
        with:
          tag: ${{ github.ref_name }} # e.g. "v1.2.3"
          artifacts: './arhiv.apk,target/release/arhiv,target/x86_64-pc-windows-gnu/release/arhiv.exe'
